$(document).ready(function() {
	function loadhomepage() {
		$("#show_iframe").load("pages/commoditySale/commodityList.html");
	};
	loadhomepage();
	$("#commodity-hot-list").on("click",function(){
		$("#show_iframe").load("pages/commoditySale/commodityHotList.html");
	});
	$("#commodity-list").on("click",function(){
		$("#show_iframe").load("pages/commoditySale/commodityList.html");
	});
	$("#commodity-label-list").on("click",function(){
		$("#show_iframe").load("pages/commoditySale/commodityLabel.html");
	});
	$("#commodity-find").on("click",function(){
		$("#show_iframe").load("pages/commoditySale/commoditySearch.html");
	});
	$("#my-will-sale-list").on("click",function(){
		$("#show_iframe").load("pages/commoditySale/commodityMySale.html");
	});
	$("#my-add-new-sale").on("click",function(){
		$("#show_iframe").load("pages/commoditySale/commodityAdd.html");
	});
	$("#my-saled-list").on("click",function(){
		$("#show_iframe").load("pages/commoditySale/commoditySold.html");
	});
	$("#my-all-order-list").on("click",function(){
		$("#show_iframe").load("pages/order/orderList.html");
	});
	$("#my-pay-order-list").on("click",function(){
		$("#show_iframe").load("pages/order/payList.html");
	});
	$("#my-confirm-order-list").on("click",function(){
		$("#show_iframe").load("pages/order/confirmList.html");
	});
	$("#my-estimate-order-list").on("click",function(){
		$("#show_iframe").load("pages/order/estimateList.html");
	});
	$("#mysalf_information").on("click",function(){
		$("#show_iframe").load("pages/shopper/main.html");
	});
	$("#find-list").on("click",function(){
		$("#show_iframe").load("pages/commodityFind/commodityList.html");
	});
	$("#find-search").on("click",function(){
		$("#show_iframe").load("pages/commodityFind/commoditySearch.html");
	});
	$("#my-add-new-find").on("click",function(){
		$("#show_iframe").load("pages/commodityFind/commodityAdd.html");
	});
	$("#my-find-List").on("click",function(){
		$("#show_iframe").load("pages/commodityFind/commodityMyFind.html");
	});
	
});
